### ISSUE TITLE
HTTPS requests not working

### ISSUE THREAD

**Issue by jwbeech** [sheehan/grails-console#27]
When running this over HTTPS the console tries to execute commands over HTTP, the browser blocks this as the page is served over HTTPS. Essentially breaking all execution of scripts.

**Comment by sheehan** [comment]
Have you set `grails.serverURL`? See https://github.com/sheehan/grails-console/issues/26

**Comment by rlovtangen** [comment]
This problem mainly occurs when doing SSL termination in a proxy in front of your application. E.g. Apache, Nginx, HAProxy, NetScaler etc in front of e.g. Tomcat. Tomcat then returns 80 for `request.serverPort` instead of 443 because the proxy is contacting Tomcat on port 80.

I solved this by configuring RemoteIpValve in Tomcat (https://tomcat.apache.org/tomcat-8.0-doc/api/org/apache/catalina/valves/RemoteIpValve.html) and sending headers `x-forwarded-for` and `x-forwarded-proto` from HAProxy. Tomcat will then return 443 for `request.serverPort`.
Using this approach, `grails.serverURL` does not need to be changed, which is a good thing IMO (might have multiple URLs to application etc). 

Another option, when using Apache, is to use AJP as protocol between Apache and Tomcat. Then `request.serverPort` will automatically be set to 443.
